# Generated by Django 5.1.2 on 2024-10-27 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_jobpost_slug'),
        ('employer', '0005_alter_employer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='qualificaiton',
            new_name='qualification',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='responsibilty',
            new_name='responsibility',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employer.employer'),
        ),
    ]
