# Generated by Django 4.2.1 on 2024-11-25 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_qualificaiton_jobpost_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='Required Skills'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='cv',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
