# Generated by Django 5.1.1 on 2024-11-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_alter_employer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='company_name',
        ),
    ]
